import { Permutation } from "./Permutation.ts";

/**
 * GroupTheory — algorithms over a finite group given as a set of elements plus a
 * binary operation and an equality test. Composes with {@link Structure} (pass
 * `structure.multiply`/`structure.add`) and {@link Permutation} (pass
 * `Permutation.compose`). Covers Cayley tables, axiom checking, element orders,
 * generated subgroups, cosets, Lagrange's index, and group actions/orbits.
 */

type BinOp<T> = (a: T, b: T) => T;
type Eq<T> = (a: T, b: T) => boolean;

const contains = <T>(arr: readonly T[], x: T, eq: Eq<T>): boolean => arr.some((y) => eq(x, y));

export class GroupTheory {
  /** The Cayley (multiplication) table: `table[i][j] = op(elements[i], elements[j])`. */
  static cayleyTable<T>(elements: readonly T[], op: BinOp<T>): T[][] {
    return elements.map((a) => elements.map((b) => op(a, b)));
  }

  /** True when the set is closed under `op`. */
  static isClosed<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>): boolean {
    for (const a of elements) for (const b of elements) if (!contains(elements, op(a, b), eq)) return false;
    return true;
  }

  /** The identity element, or `null` if none exists. */
  static findIdentity<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>): T | null {
    for (const e of elements) {
      if (elements.every((a) => eq(op(e, a), a) && eq(op(a, e), a))) return e;
    }
    return null;
  }

  /** True when `op` is associative over the set (O(n³) check). */
  static isAssociative<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>): boolean {
    for (const a of elements)
      for (const b of elements) for (const c of elements) if (!eq(op(op(a, b), c), op(a, op(b, c)))) return false;
    return true;
  }

  /** True when every element has an inverse relative to `identity`. */
  static hasInverses<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>, identity: T): boolean {
    return elements.every((a) => elements.some((b) => eq(op(a, b), identity) && eq(op(b, a), identity)));
  }

  /** Verify all four group axioms (closure, associativity, identity, inverses). */
  static isGroup<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>): boolean {
    if (!GroupTheory.isClosed(elements, op, eq)) return false;
    const id = GroupTheory.findIdentity(elements, op, eq);
    if (id === null) return false;
    return GroupTheory.isAssociative(elements, op, eq) && GroupTheory.hasInverses(elements, op, eq, id);
  }

  /** True when the group is also abelian (commutative). */
  static isAbelian<T>(elements: readonly T[], op: BinOp<T>, eq: Eq<T>): boolean {
    for (const a of elements) for (const b of elements) if (!eq(op(a, b), op(b, a))) return false;
    return true;
  }

  /** The order of an element: the least `k ≥ 1` with `elementᵏ = identity`. */
  static elementOrder<T>(element: T, op: BinOp<T>, eq: Eq<T>, identity: T, max = 100000): number {
    let acc = element;
    for (let k = 1; k <= max; k++) {
      if (eq(acc, identity)) return k;
      acc = op(acc, element);
    }
    throw new Error("Element order exceeded the search bound (is the group finite?).");
  }

  /**
   * The subgroup generated by `generators`: the closure of the generators (and
   * the identity) under `op`. `identity` may be supplied when it is not itself a
   * generator; otherwise closure alone recovers it for a finite group.
   */
  static closure<T>(generators: readonly T[], op: BinOp<T>, eq: Eq<T>, cap = 100000): T[] {
    const elements: T[] = [];
    for (const g of generators) if (!contains(elements, g, eq)) elements.push(g);
    let changed = true;
    while (changed) {
      changed = false;
      for (let i = 0; i < elements.length; i++) {
        for (const g of generators) {
          const p = op(elements[i] as T, g);
          if (!contains(elements, p, eq)) {
            elements.push(p);
            changed = true;
            if (elements.length > cap) throw new Error("Closure exceeded the size cap.");
          }
        }
      }
    }
    return elements;
  }

  /** True when `sub` is a subgroup of `group` under `op`. */
  static isSubgroup<T>(sub: readonly T[], group: readonly T[], op: BinOp<T>, eq: Eq<T>): boolean {
    if (!sub.every((s) => contains(group, s, eq))) return false;
    return GroupTheory.isGroup(sub, op, eq);
  }

  /** The distinct left cosets `gH` of subgroup `H` in `group`. */
  static leftCosets<T>(subgroup: readonly T[], group: readonly T[], op: BinOp<T>, eq: Eq<T>): T[][] {
    const cosets: T[][] = [];
    const seen: T[] = [];
    for (const g of group) {
      if (contains(seen, g, eq)) continue;
      const coset = subgroup.map((h) => op(g, h));
      cosets.push(coset);
      for (const c of coset) if (!contains(seen, c, eq)) seen.push(c);
    }
    return cosets;
  }

  /** Lagrange index `[G : H] = |G| / |H|`. */
  static index<T>(group: readonly T[], subgroup: readonly T[]): number {
    return group.length / subgroup.length;
  }

  /** The orbit of `x` under a group action, given the generators and the action map. */
  static orbit<T, X>(x: X, generators: readonly T[], action: (g: T, x: X) => X, eqX: Eq<X>, cap = 100000): X[] {
    const orbit: X[] = [x];
    let changed = true;
    while (changed) {
      changed = false;
      for (let i = 0; i < orbit.length; i++) {
        for (const g of generators) {
          const y = action(g, orbit[i] as X);
          if (!contains(orbit, y, eqX)) {
            orbit.push(y);
            changed = true;
            if (orbit.length > cap) throw new Error("Orbit exceeded the size cap.");
          }
        }
      }
    }
    return orbit;
  }

  /** The cyclic group Zₙ as `{0, …, n-1}` under addition mod n. */
  static cyclicGroup(n: number): { elements: number[]; op: BinOp<number>; identity: number } {
    return {
      elements: Array.from({ length: n }, (_, i) => i),
      op: (a, b) => (a + b) % n,
      identity: 0,
    };
  }

  /** The symmetric group Sₙ: every permutation of `{0, …, n-1}`. */
  static symmetricGroup(n: number): Array<Permutation<number>> {
    const domain = Array.from({ length: n }, (_, i) => i);
    const results: Array<Permutation<number>> = [];
    const permute = (arr: number[], k: number) => {
      if (k === arr.length) {
        results.push(new Permutation(domain, [...arr]));
        return;
      }
      for (let i = k; i < arr.length; i++) {
        [arr[k], arr[i]] = [arr[i], arr[k]];
        permute(arr, k + 1);
        [arr[k], arr[i]] = [arr[i], arr[k]];
      }
    };
    permute([...domain], 0);
    return results;
  }
}
